name: Fliff Betting Bot

on:
  schedule:
    # Run every hour at the top of the hour
    - cron: '0 * * * *'
  workflow_dispatch:  # Allow manual runs

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install chromium

    - name: Run Fliff Bot
      run: |
        python fliff-bot/main.py
      env:
        FLIFF_USERNAME: ${{ secrets.FLIFF_USERNAME }}
        FLIFF_PASSWORD: ${{ secrets.FLIFF_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}